services:
  postgres:
    image: postgres:16-alpine
    container_name: zoomind_fastapi_postgres
    environment:
      POSTGRES_DB: zoomind_fastapi
      POSTGRES_USER: zoomind_fastapi
      POSTGRES_PASSWORD: zoomind_fastapi
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: zoomind_fastapi_redis
    ports:
      - "6380:6379"

volumes:
  postgres_data: