"""create products table

Revision ID: 3f1bb7afce02
Revises: 2ef82a0281e8
Create Date: 2026-06-29 19:40:11.968675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1bb7afce02'
down_revision: Union[str, Sequence[str], None] = '2ef82a0281e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.Enum('food', 'toy', 'accessory', 'medicine', 'other', name='productcategory'), nullable=False),
    sa.Column('species', sa.Enum('dog', 'cat', 'parrot', 'universal', 'other', name='productspecies'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_table('products')
    sa.Enum(name='productspecies').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='productcategory').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
