"""add total price to orders

Revision ID: 48c2f73fea60
Revises: 217b6ec3b113
Create Date: 2026-07-04 18:48:13.301874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c2f73fea60'
down_revision: Union[str, Sequence[str], None] = '217b6ec3b113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
