"""add user profile fields

Revision ID: 66ab8b370153
Revises: b3f8de0145cd
Create Date: 2026-07-13 16:22:28.778884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ab8b370153'
down_revision: Union[str, Sequence[str], None] = 'b3f8de0145cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column(
        'users',
        sa.Column(
            'delivery_address',
            sa.String(length=255),
            server_default=sa.text("''"),
            nullable=False,
        ),
    )
    op.add_column(
        'users',
        sa.Column(
            'is_newsletter_enabled',
            sa.Boolean(),
            server_default=sa.text('false'),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_newsletter_enabled')
    op.drop_column('users', 'delivery_address')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
