"""replace pet age with birth date

Revision ID: b3f8de0145cd
Revises: d534b9fa8077
Create Date: 2026-07-12 14:21:27.986050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f8de0145cd'
down_revision: Union[str, Sequence[str], None] = 'd534b9fa8077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('birth_date', sa.Date(), nullable=True))
    op.execute(
        """
        UPDATE pets
        SET birth_date = CURRENT_DATE - (age * INTERVAL '1 year')
        """
    )
    op.alter_column('pets', 'birth_date', nullable=False)
    op.drop_column('pets', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE pets
        SET age = EXTRACT(YEAR FROM age(CURRENT_DATE, birth_date))::INTEGER
        """
    )

    op.alter_column('pets', 'age', nullable=False)
    op.drop_column('pets', 'birth_date')
    # ### end Alembic commands ###
