"""add order reminder fields

Revision ID: d534b9fa8077
Revises: ea4ff5071201
Create Date: 2026-07-09 18:37:45.740443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd534b9fa8077'
down_revision: Union[str, Sequence[str], None] = 'ea4ff5071201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'reminder_sent_at')
    op.drop_column('orders', 'delivered_at')
    # ### end Alembic commands ###
